check we're not going to over write configuraton.nix changes

diff --git a/nixos-conf-pull b/nixos-conf-pull
--- a/nixos-conf-pull
+++ b/nixos-conf-pull
@@ -3,7 +3,14 @@ set -eu
 set -o pipefail
 
 directory=/etc/nixos
+configuration=$directory/configuration.nix
+host_configuration=$directory/$(hostname)/configuration.nix
+
+if ! diff $configuration $host_configuration >/dev/null; then
+    echo "Error: there are local changes to $configuration"
+    exit 1
+fi
 
 git pull
-cp $directory/"$(hostname)"/configuration.nix $directory/configuration.nix
+cp $host_configuration $configuration
 
diff --git a/nixos-conf-push b/nixos-conf-push
--- a/nixos-conf-push
+++ b/nixos-conf-push
@@ -3,6 +3,8 @@ set -eu
 set -o pipefail
 
 directory=/etc/nixos
+configuration=$directory/configuration.nix
+host_configuration=$directory/$(hostname)/configuration.nix
 
 message="${1:-}"
 if [ -z "$message" ]; then
@@ -10,7 +12,12 @@ if [ -z "$message" ]; then
     exit 1
 fi
 
-cp $directory/configuration.nix $directory/"$(hostname)"/configuration.nix 
+if [ -n "$(git diff "$host_configuration")" ]; then 
+    echo "Error there are local changes to $host_configuration"
+    exit 1
+fi
+
+cp $configuration $host_configuration
 git add -A
 git commit -m "$message"
 git push origin master
