support hardware-configuraton.nix

diff --git a/nixos-conf-pull b/nixos-conf-pull
--- a/nixos-conf-pull
+++ b/nixos-conf-pull
@@ -3,14 +3,17 @@ set -eu
 set -o pipefail
 
 directory=/etc/nixos
-configuration=$directory/configuration.nix
-host_configuration=$directory/$(hostname)/configuration.nix
+host_directory=$directory/$(hostname)
 
-if ! diff $configuration $host_configuration >/dev/null; then
-    echo "Error: there are local changes to $configuration"
+for file in $(ls $host_directory); do
+  if ! diff $directory/$file $host_directory/$file >/dev/null; then
+    echo "Error: there are local changes to $directory/$file"
     exit 1
-fi
+  fi
+done
+
+exit 0
 
 git pull
-cp $host_configuration $configuration
+cp $host_directory/* $directory
 
diff --git a/nixos-conf-push b/nixos-conf-push
--- a/nixos-conf-push
+++ b/nixos-conf-push
@@ -3,8 +3,7 @@ set -eu
 set -o pipefail
 
 directory=/etc/nixos
-configuration=$directory/configuration.nix
-host_configuration=$directory/$(hostname)/configuration.nix
+host_directory=$directory/$(hostname)
 
 message="${1:-}"
 if [ -z "$message" ]; then
@@ -12,12 +11,14 @@ if [ -z "$message" ]; then
     exit 1
 fi
 
-if [ -n "$(git diff "$host_configuration")" ]; then 
-    echo "Error there are local changes to $host_configuration"
-    exit 1
-fi
+for file in $(ls $host_directory); do
+    if [ -n "$(git diff "$host_directory/$file")" ]; then 
+      echo "Error there are local changes to $file"
+      exit 1
+    fi
+    cp $directory/$file $host_directory
+done
 
-cp $configuration $host_configuration
 git add -A
 git commit -m "$message"
 git push origin master
